### PR TITLE
fix(positioning): make sure tooltip is oriented correctly when close to edge

### LINKED ISSUE #371: Incorrect tooltip positioning in corner cases
Tooltip won't display correctly when close to top-left and top-right corner of the browser window.

How to reproduce:
- align the hoverable area to be near the top-right corner of the window
- position mouse cursor above the hoverable area
- move cursor down until it is inside of the hoverable area
- tooltip will be displayed with incorrect position

Following picture was taken from http://wwayne.com/react-tooltip/
image

### PR DESCRIPTION
**Pull request by hassanbot**
We now check different tooltip orientations to make sure the best one is chosen. There are 2 cases that lead to reorientation:
1.  If the desired orientation (`desiredPlace`) is completely inside the client window, and the current orientation (`place`) is different from the desired one (then **reorient to the desired orientation**)

2.  If neither the desired orientation (`desiredPlace`) nor the current one (`place`) is inside the client window, but there are other orientations that are (then **reorient to an arbitrary orientation that is inside**)

All other cases will keep the orientation as it was before.

Fixes #371

### CODE REVIEW

File: src/utils/getPosition.js [hunk 1]
```diff
@@ -52,139 +52,55 @@ export default function (e, target, node, place, desiredPlace, effect, offset) {
...
+  let outsideLeft = p => getTipOffsetLeft(p) < 0
+  let outsideRight = p => getTipOffsetRight(p) > windowWidth
+  let outsideTop = p => getTipOffsetTop(p) < 0
+  let outsideBottom = p => getTipOffsetBottom(p) > windowHeight
+
+  // Check whether the tooltip with orientation p is completely inside the client window
+  let outside = p => outsideLeft(p) || outsideRight(p) || outsideTop(p) || outsideBottom(p)
+  let inside = p => !outside(p)
+
+  let placesList = ['left', 'right', 'top', 'bottom']
```
Comment (aronhelser) [inline src/utils/getPosition.js]: I think we might want 'top' and 'bottom' to have priority - they will if you list them first, right?

I really like how you've simplified the code - it's much clearer. I still need to try it out (or someone does)

Comment (aronhelser) [reply src/utils/getPosition.js]: Oh, and please format the first line of you commit message for semantic versioning:

'fix(positioning): make sure ...'

If you do, travis will do an automatic release.

Comment (hassanbot) [reply src/utils/getPosition.js]: I've changed the pull request title now, is that enough?

You're right about the orientation priority, it's changed with 6f01ed8dfcb25823daca3688563454c9589f971c

**Comment by aronhelser** [comment]
I was able to test, and it looks good. It also fixes the problem with entering from the top. Merging!

**Comment by aronhelser** [comment]
I'm sorry, I don't understand. Can you provide an example or steps to reproduce the problem?

**Comment by aronhelser** [comment]
And potentially file an issue...

**Comment by TotallWAR** [comment]
image

As you can see, reposition works perfectly, however both of pseudo elements (for both posotions) are shown

**Comment by TotallWAR** [comment]
image

It's an example without reposition, when it works default.

**Comment by TotallWAR** [comment]
Any ideas?
